language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
service:
 - docker
install:
 - nvm install 8.5.0
 - nvm use 8.5.0
 - sh install.sh
script:
 - dotnet test ./Ploker.Domain.Test
after_success:
 - sh build_publish.sh 
 - sh docker.sh